//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietdatdichvu
    {
        public long IDDV { get; set; }
        public long IDDAT { get; set; }
        public int Soluong { get; set; }
    
        public virtual Dichvu Dichvu { get; set; }
        public virtual Datphong Datphong { get; set; }
    }
}
