//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadon
    {
        public long MaHD { get; set; }
        public double Tienphong { get; set; }
        public double Tiendichvu { get; set; }
        public double VAT { get; set; }
        public Nullable<double> Khuyenmai { get; set; }
        public System.DateTime Ngaylap { get; set; }
        public long IDDAT { get; set; }
    
        public virtual Datphong Datphong { get; set; }
    }
}
