//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLKhachsanEntities : DbContext
    {
        public QLKhachsanEntities()
            : base("name=QLKhachsanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chitietdatdichvu> Chitietdatdichvus { get; set; }
        public virtual DbSet<Chitietdatphong> Chitietdatphongs { get; set; }
        public virtual DbSet<Datphong> Datphongs { get; set; }
        public virtual DbSet<Dichvu> Dichvus { get; set; }
        public virtual DbSet<Hoadon> Hoadons { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<Loaiphong> Loaiphongs { get; set; }
        public virtual DbSet<Nhanvien> Nhanviens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual ObjectResult<KTMANV_Result> KTMANV(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KTMANV_Result>("KTMANV", manvParameter);
        }
    
        public virtual int LOADDEVICEROOM(Nullable<long> number)
        {
            var numberParameter = number.HasValue ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOADDEVICEROOM", numberParameter);
        }
    
        public virtual ObjectResult<LOADROOMID_Result> LOADROOMID(Nullable<int> number)
        {
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADROOMID_Result>("LOADROOMID", numberParameter);
        }
    
        public virtual ObjectResult<LOADROOMRANH_Result> LOADROOMRANH(string loaip)
        {
            var loaipParameter = loaip != null ?
                new ObjectParameter("loaip", loaip) :
                new ObjectParameter("loaip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADROOMRANH_Result>("LOADROOMRANH", loaipParameter);
        }
    
        public virtual int LuuHoaDon(Nullable<double> tienphong, Nullable<double> tiendv, Nullable<double> vat, Nullable<double> khuyemai, Nullable<System.DateTime> ngaylap, Nullable<long> iDdat)
        {
            var tienphongParameter = tienphong.HasValue ?
                new ObjectParameter("tienphong", tienphong) :
                new ObjectParameter("tienphong", typeof(double));
    
            var tiendvParameter = tiendv.HasValue ?
                new ObjectParameter("tiendv", tiendv) :
                new ObjectParameter("tiendv", typeof(double));
    
            var vatParameter = vat.HasValue ?
                new ObjectParameter("vat", vat) :
                new ObjectParameter("vat", typeof(double));
    
            var khuyemaiParameter = khuyemai.HasValue ?
                new ObjectParameter("khuyemai", khuyemai) :
                new ObjectParameter("khuyemai", typeof(double));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            var iDdatParameter = iDdat.HasValue ?
                new ObjectParameter("IDdat", iDdat) :
                new ObjectParameter("IDdat", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LuuHoaDon", tienphongParameter, tiendvParameter, vatParameter, khuyemaiParameter, ngaylapParameter, iDdatParameter);
        }
    
        public virtual ObjectResult<SEARCHUSER_Result> SEARCHUSER(string hoten)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCHUSER_Result>("SEARCHUSER", hotenParameter);
        }
    
        public virtual ObjectResult<SP_CTDATDV_Result> SP_CTDATDV(Nullable<long> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CTDATDV_Result>("SP_CTDATDV", idhdParameter);
        }
    
        public virtual ObjectResult<SP_CTDATPHONG_Result> SP_CTDATPHONG(Nullable<long> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CTDATPHONG_Result>("SP_CTDATPHONG", idhdParameter);
        }
    
        public virtual ObjectResult<SP_LOGIN_Result> SP_LOGIN(string accout, string password)
        {
            var accoutParameter = accout != null ?
                new ObjectParameter("accout", accout) :
                new ObjectParameter("accout", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOGIN_Result>("SP_LOGIN", accoutParameter, passwordParameter);
        }
    
        public virtual int SP_THEMDAT(string ngaylap, string manv, string cmt, string ghichu)
        {
            var ngaylapParameter = ngaylap != null ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var cmtParameter = cmt != null ?
                new ObjectParameter("cmt", cmt) :
                new ObjectParameter("cmt", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMDAT", ngaylapParameter, manvParameter, cmtParameter, ghichuParameter);
        }
    
        public virtual int THEMDV(string tendv, Nullable<double> gia, string dvt, string hinh, string mota)
        {
            var tendvParameter = tendv != null ?
                new ObjectParameter("Tendv", tendv) :
                new ObjectParameter("Tendv", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(double));
    
            var dvtParameter = dvt != null ?
                new ObjectParameter("dvt", dvt) :
                new ObjectParameter("dvt", typeof(string));
    
            var hinhParameter = hinh != null ?
                new ObjectParameter("hinh", hinh) :
                new ObjectParameter("hinh", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMDV", tendvParameter, giaParameter, dvtParameter, hinhParameter, motaParameter);
        }
    
        public virtual ObjectResult<THONGKETHANG_Result> THONGKETHANG(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONGKETHANG_Result>("THONGKETHANG", ngayParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> TIENDICHVU(Nullable<long> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TIENDICHVU", idhdParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> TIENPHONG(Nullable<long> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TIENPHONG", idhdParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> TIENTHEOHD(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TIENTHEOHD", idParameter);
        }
    
        public virtual ObjectResult<TIMKH_Result> TIMKH(string cMT)
        {
            var cMTParameter = cMT != null ?
                new ObjectParameter("CMT", cMT) :
                new ObjectParameter("CMT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TIMKH_Result>("TIMKH", cMTParameter);
        }
    }
}
