//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string Taikhoan1 { get; set; }
        public string MaNV { get; set; }
        public string Matkhau { get; set; }
        public string Nhom { get; set; }
        public System.DateTime Ngaylap { get; set; }
    
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
